name: mobile
description: Highweh mobile client

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^2.5.1
  cupertino_icons: ^0.1.3
  dartz: ^0.10.0
  device_info: ^1.0.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.12.4
  flutter_statusbarcolor: ^0.2.3
  flutter_user_agent: ^1.2.2
  form_field_validator: ^1.0.1
  freezed_annotation: ^0.12.0
  gestures: ^0.0.1
  intl: ^0.16.1
  intl_phone_number_input: ^0.5.2+2
  json_annotation: ^3.1.1

  #google map
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0

  logging: ^1.0.1

  modal_progress_hud: ^0.1.3
  path_provider: ^1.6.24
  pie_chart: ^4.0.1
  pin_code_fields: ^6.0.1
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.2+1
  flash: ^2.0.1

dev_dependencies:
  ## HTTP Client
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.8.1
  flutter_secure_storage: ^4.2.1
  flutter_test:
    sdk: flutter

  ## Unions
  freezed: ^0.12.7
  json_serializable: ^3.5.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Highweh.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/
    - assets/images/
    - assets/fonts/
    - assets/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
