name: mobile
description: Highweh mobile client

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: ^0.4.8

  intl_phone_number_input: ^0.5.2+2

# For gesture
  gestures: ^0.0.1

  # For pin input filed
  pin_code_fields: ^6.0.1

   # To pick image from phone or camera
  image_picker: ^0.6.7+14

  pie_chart: ^4.0.1
   

  


 
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
        # - assets/ 
     
      - assets/images/
      - assets/fonts/
      


 
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        
       
   
